# Generated by Django 3.1 on 2022-06-06 07:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ixtisas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80)),
                ('kod', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('ata_adi', models.CharField(max_length=50)),
                ('tehsil', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('migistr', 'Magistr'), ('doktorant', 'Doktorant')], max_length=25)),
                ('elmi_derece', models.CharField(blank=True, choices=[('fd', 'Felsefe Doktoru'), ('ed', 'Elmler DOktoru')], max_length=25, null=True)),
                ('vezife', models.CharField(blank=True, choices=[('assis', 'Assistent'), ('bm', 'Bas Muellim'), ('d', 'Dossent'), ('p', 'Professor')], max_length=25, null=True)),
                ('gender', models.CharField(blank=True, choices=[('k', 'Kisi'), ('q', 'Qadin')], max_length=25, null=True)),
                ('fenler', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('bolme', models.CharField(choices=[('az', 'AZE'), ('ru', 'RUS'), ('eng', 'ENG')], max_length=25)),
                ('dogum_tarixi', models.CharField(blank=True, max_length=25, null=True)),
                ('doguldugu_yer', models.CharField(blank=True, max_length=25, null=True)),
                ('bitirdiyi_universitet', models.CharField(max_length=50)),
                ('aile_vezyeti', models.CharField(choices=[('e', 'Evli'), ('s', 'Subay')], max_length=25)),
                ('partiya_mensubiyeti', models.CharField(blank=True, max_length=150, null=True)),
                ('main_work', models.CharField(blank=True, max_length=150, null=True)),
                ('herbi_mukellefiyet', models.BooleanField()),
                ('faktiki_yasaadigi_unvan', models.CharField(max_length=250)),
                ('qeydiyatda_oldugu_unvan', models.CharField(max_length=250)),
                ('ixtisas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.ixtisas')),
            ],
        ),
    ]
