# Generated by Django 3.1 on 2022-06-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeqaleTipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Meqale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hem_muellifler', models.CharField(blank=True, max_length=255, null=True)),
                ('cap_olundugu_jurnal', models.CharField(blank=True, max_length=250, null=True)),
                ('ili', models.IntegerField(max_length=10)),
                ('sehfesi', models.IntegerField(max_length=25)),
                ('index_nom', models.CharField(max_length=15)),
                ('meqalenin_cap_oldugu_yer', models.CharField(max_length=150)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.meqaletipi')),
            ],
        ),
    ]
